stages:
  - test

tests:
  stage: test
  tags: 
    - ios
  script:
    - xcodebuild -scheme 'elixxir-dapps-sdk-swift-Package' -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 13' test
