stages:
  - test

tests:
  stage: test
  tags: 
    - ios
  script:
    - echo -e "section_start:`date +%s`:test_macos\r\e[0KRun tests on macOS"
    - ./run-tests.sh macos
    - echo -e "section_end:`date +%s`:test_macos\r\e[0K"
    - echo -e "section_start:`date +%s`:test_ios\r\e[0KRun tests on iOS Simulator"
    - ./run-tests.sh ios
    - echo -e "section_end:`date +%s`:test_ios\r\e[0K"
