stages:
  - test

test-package-macos:
  stage: test
  tags: 
    - ios
  script:
    - ./run-tests.sh macos

test-package-ios:
  stage: test
  tags: 
    - ios
  script:
    - ./run-tests.sh ios

test-examples-ios:
  stage: test
  tags: 
    - ios
  script:
    - ./run-tests.sh ios-examples
