before_script:
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - echo $PWD
  - swift --version
  - xcodebuild -version
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -t rsa $GITLAB_SERVER > ~/.ssh/known_hosts
  - ./xcode-remove-caches.sh

stages:
  - test

test-package-macos:
  stage: test
  tags: 
    - ios
  script:
    - ./run-tests.sh macos
  retry: 1

test-package-ios:
  stage: test
  tags: 
    - ios
  script:
    - ./run-tests.sh ios
  retry: 1

test-examples-ios:
  stage: test
  tags: 
    - ios
  script:
    - ./run-tests.sh examples-ios
  retry: 1
