stages:
  - test

package-tests:
  stage: test
  tags: 
    - ios
  script:
    - ./run-tests.sh
  retry: 1

examples-tests:
  stage: test
  tags: 
    - ios
  script:
    - ./run-tests.sh examples
  retry: 1
